version: "3.7"

services:
  havid-19:
    image: techblog/havid-19
    container_name: havid-19
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - API_KEY= #Telegram BOT API
      - ALLOWED_IDS= #Your Telegram ID (Get is using @myidbot)
      - USER_ID= #parents.education.gov.il portal user
      - USER_KEY= #parents.education.gov.il portal password
   ports:
      - "6700:6700"
